/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_account = 1,
  anon_sym_include = 2,
  anon_sym_SEMI = 3,
  anon_sym_POUND = 4,
  anon_sym_STAR = 5,
  sym_include_path = 6,
  sym_account_name_segment = 7,
  sym__account_name_separator = 8,
  sym__comment_word = 9,
  sym__spaces1 = 10,
  sym__spaces2 = 11,
  sym__newline = 12,
  sym_source_file = 13,
  sym__definition = 14,
  sym__directive = 15,
  sym_account_directive = 16,
  sym_include_directive = 17,
  sym_account_name = 18,
  sym_inline_comment = 19,
  sym_comment = 20,
  sym__comment_content = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_account_name_repeat1 = 23,
  aux_sym__comment_content_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_account] = "account",
  [anon_sym_include] = "include",
  [anon_sym_SEMI] = ";",
  [anon_sym_POUND] = "#",
  [anon_sym_STAR] = "*",
  [sym_include_path] = "include_path",
  [sym_account_name_segment] = "account_name_segment",
  [sym__account_name_separator] = "_account_name_separator",
  [sym__comment_word] = "_comment_word",
  [sym__spaces1] = "_spaces1",
  [sym__spaces2] = "_spaces2",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__directive] = "_directive",
  [sym_account_directive] = "account_directive",
  [sym_include_directive] = "include_directive",
  [sym_account_name] = "account_name",
  [sym_inline_comment] = "inline_comment",
  [sym_comment] = "comment",
  [sym__comment_content] = "_comment_content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_account_name_repeat1] = "account_name_repeat1",
  [aux_sym__comment_content_repeat1] = "_comment_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_account] = anon_sym_account,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_include_path] = sym_include_path,
  [sym_account_name_segment] = sym_account_name_segment,
  [sym__account_name_separator] = sym__account_name_separator,
  [sym__comment_word] = sym__comment_word,
  [sym__spaces1] = sym__spaces1,
  [sym__spaces2] = sym__spaces2,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__directive] = sym__directive,
  [sym_account_directive] = sym_account_directive,
  [sym_include_directive] = sym_include_directive,
  [sym_account_name] = sym_account_name,
  [sym_inline_comment] = sym_inline_comment,
  [sym_comment] = sym_comment,
  [sym__comment_content] = sym__comment_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_account_name_repeat1] = aux_sym_account_name_repeat1,
  [aux_sym__comment_content_repeat1] = aux_sym__comment_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_account] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_include_path] = {
    .visible = true,
    .named = true,
  },
  [sym_account_name_segment] = {
    .visible = true,
    .named = true,
  },
  [sym__account_name_separator] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_word] = {
    .visible = false,
    .named = true,
  },
  [sym__spaces1] = {
    .visible = false,
    .named = true,
  },
  [sym__spaces2] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__directive] = {
    .visible = false,
    .named = true,
  },
  [sym_account_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_account_name] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_content] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_account_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__comment_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_account_name = 1,
  field_comment = 2,
  field_include_path = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_account_name] = "account_name",
  [field_comment] = "comment",
  [field_include_path] = "include_path",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_account_name, 2},
  [1] =
    {field_include_path, 2},
  [2] =
    {field_account_name, 2},
    {field_comment, 3},
  [4] =
    {field_comment, 3},
    {field_include_path, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 30,
        ' ', 28,
        '#', 22,
        '*', 23,
        ':', 26,
        ';', 21,
        'a', 5,
        'i', 10,
      );
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == ':') ADVANCE(26);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(24);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == ';') ADVANCE(21);
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_account);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_include_path);
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_account_name_segment);
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__account_name_separator);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__spaces1);
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__spaces2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 17},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_account] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym__account_name_separator] = ACTIONS(1),
    [sym__spaces1] = ACTIONS(1),
    [sym__spaces2] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(23),
    [sym__definition] = STATE(3),
    [sym__directive] = STATE(3),
    [sym_account_directive] = STATE(24),
    [sym_include_directive] = STATE(24),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_account] = ACTIONS(5),
    [anon_sym_include] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [sym__spaces1] = ACTIONS(11),
    [sym__newline] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(2),
    [sym__directive] = STATE(2),
    [sym_account_directive] = STATE(24),
    [sym_include_directive] = STATE(24),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_account] = ACTIONS(17),
    [anon_sym_include] = ACTIONS(20),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(23),
    [sym__spaces1] = ACTIONS(26),
    [sym__newline] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(2),
    [sym__directive] = STATE(2),
    [sym_account_directive] = STATE(24),
    [sym_include_directive] = STATE(24),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(32),
    [anon_sym_account] = ACTIONS(5),
    [anon_sym_include] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [sym__spaces1] = ACTIONS(11),
    [sym__newline] = ACTIONS(34),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(38), 1,
      sym__spaces1,
    STATE(5), 1,
      aux_sym__comment_content_repeat1,
    ACTIONS(36), 7,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__newline,
  [16] = 3,
    ACTIONS(38), 1,
      sym__spaces1,
    STATE(6), 1,
      aux_sym__comment_content_repeat1,
    ACTIONS(40), 7,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__newline,
  [32] = 3,
    ACTIONS(44), 1,
      sym__spaces1,
    STATE(6), 1,
      aux_sym__comment_content_repeat1,
    ACTIONS(42), 7,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__newline,
  [48] = 2,
    ACTIONS(49), 1,
      sym__spaces1,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__newline,
  [61] = 1,
    ACTIONS(51), 8,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__spaces1,
      sym__newline,
  [72] = 1,
    ACTIONS(53), 8,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__spaces1,
      sym__newline,
  [83] = 1,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__spaces1,
      sym__newline,
  [94] = 1,
    ACTIONS(42), 8,
      ts_builtin_sym_end,
      anon_sym_account,
      anon_sym_include,
      anon_sym_SEMI,
      anon_sym_POUND,
      anon_sym_STAR,
      sym__spaces1,
      sym__newline,
  [105] = 3,
    ACTIONS(57), 1,
      sym__account_name_separator,
    STATE(12), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(60), 2,
      sym__spaces2,
      sym__newline,
  [116] = 3,
    ACTIONS(62), 1,
      sym__account_name_separator,
    STATE(14), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(64), 2,
      sym__spaces2,
      sym__newline,
  [127] = 3,
    ACTIONS(62), 1,
      sym__account_name_separator,
    STATE(12), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(66), 2,
      sym__spaces2,
      sym__newline,
  [138] = 3,
    ACTIONS(68), 1,
      sym__spaces2,
    ACTIONS(70), 1,
      sym__newline,
    STATE(28), 1,
      sym_inline_comment,
  [148] = 3,
    ACTIONS(68), 1,
      sym__spaces2,
    ACTIONS(72), 1,
      sym__newline,
    STATE(31), 1,
      sym_inline_comment,
  [158] = 1,
    ACTIONS(60), 3,
      sym__account_name_separator,
      sym__spaces2,
      sym__newline,
  [164] = 1,
    ACTIONS(74), 2,
      anon_sym_SEMI,
      anon_sym_POUND,
  [169] = 2,
    ACTIONS(76), 1,
      sym__comment_word,
    STATE(9), 1,
      sym__comment_content,
  [176] = 2,
    ACTIONS(78), 1,
      sym_account_name_segment,
    STATE(15), 1,
      sym_account_name,
  [183] = 2,
    ACTIONS(80), 1,
      sym__spaces1,
    ACTIONS(82), 1,
      sym__newline,
  [190] = 2,
    ACTIONS(76), 1,
      sym__comment_word,
    STATE(33), 1,
      sym__comment_content,
  [197] = 1,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
  [201] = 1,
    ACTIONS(86), 1,
      sym__newline,
  [205] = 1,
    ACTIONS(88), 1,
      sym__spaces1,
  [209] = 1,
    ACTIONS(90), 1,
      sym_account_name_segment,
  [213] = 1,
    ACTIONS(92), 1,
      sym__newline,
  [217] = 1,
    ACTIONS(94), 1,
      sym__newline,
  [221] = 1,
    ACTIONS(96), 1,
      sym__comment_word,
  [225] = 1,
    ACTIONS(98), 1,
      sym_include_path,
  [229] = 1,
    ACTIONS(100), 1,
      sym__newline,
  [233] = 1,
    ACTIONS(102), 1,
      sym__spaces1,
  [237] = 1,
    ACTIONS(104), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 16,
  [SMALL_STATE(6)] = 32,
  [SMALL_STATE(7)] = 48,
  [SMALL_STATE(8)] = 61,
  [SMALL_STATE(9)] = 72,
  [SMALL_STATE(10)] = 83,
  [SMALL_STATE(11)] = 94,
  [SMALL_STATE(12)] = 105,
  [SMALL_STATE(13)] = 116,
  [SMALL_STATE(14)] = 127,
  [SMALL_STATE(15)] = 138,
  [SMALL_STATE(16)] = 148,
  [SMALL_STATE(17)] = 158,
  [SMALL_STATE(18)] = 164,
  [SMALL_STATE(19)] = 169,
  [SMALL_STATE(20)] = 176,
  [SMALL_STATE(21)] = 183,
  [SMALL_STATE(22)] = 190,
  [SMALL_STATE(23)] = 197,
  [SMALL_STATE(24)] = 201,
  [SMALL_STATE(25)] = 205,
  [SMALL_STATE(26)] = 209,
  [SMALL_STATE(27)] = 213,
  [SMALL_STATE(28)] = 217,
  [SMALL_STATE(29)] = 221,
  [SMALL_STATE(30)] = 225,
  [SMALL_STATE(31)] = 229,
  [SMALL_STATE(32)] = 233,
  [SMALL_STATE(33)] = 237,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_content, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_content, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_content_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comment_content_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_account_name_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_account_name_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_name, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_name, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_directive, 3, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 3, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_comment, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_directive, 4, 0, 3),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 4, 0, 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_comment, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hledger(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hledger",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 5,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
