/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_account = 1,
  anon_sym_COLON = 2,
  anon_sym_SEMI = 3,
  anon_sym_POUND = 4,
  anon_sym_COMMA = 5,
  sym_account_name_segment = 6,
  sym__comment_word = 7,
  sym_tag_key = 8,
  sym_tag_value = 9,
  sym__spaces1 = 10,
  sym__spaces2 = 11,
  sym__newline = 12,
  sym_source_file = 13,
  sym__definition = 14,
  sym_account_directive = 15,
  sym_account_name = 16,
  sym__inline_comment = 17,
  sym_comment = 18,
  sym__comment = 19,
  sym_tag = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_account_name_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_account] = "account",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_POUND] = "#",
  [anon_sym_COMMA] = ",",
  [sym_account_name_segment] = "account_name_segment",
  [sym__comment_word] = "_comment_word",
  [sym_tag_key] = "tag_key",
  [sym_tag_value] = "tag_value",
  [sym__spaces1] = "_spaces1",
  [sym__spaces2] = "_spaces2",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_account_directive] = "account_directive",
  [sym_account_name] = "account_name",
  [sym__inline_comment] = "_inline_comment",
  [sym_comment] = "comment",
  [sym__comment] = "_comment",
  [sym_tag] = "tag",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_account_name_repeat1] = "account_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_account] = anon_sym_account,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_account_name_segment] = sym_account_name_segment,
  [sym__comment_word] = sym__comment_word,
  [sym_tag_key] = sym_tag_key,
  [sym_tag_value] = sym_tag_value,
  [sym__spaces1] = sym__spaces1,
  [sym__spaces2] = sym__spaces2,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_account_directive] = sym_account_directive,
  [sym_account_name] = sym_account_name,
  [sym__inline_comment] = sym__inline_comment,
  [sym_comment] = sym_comment,
  [sym__comment] = sym__comment,
  [sym_tag] = sym_tag,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_account_name_repeat1] = aux_sym_account_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_account] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_account_name_segment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_word] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_key] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_value] = {
    .visible = true,
    .named = true,
  },
  [sym__spaces1] = {
    .visible = false,
    .named = true,
  },
  [sym__spaces2] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_account_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_account_name] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_account_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_account_name = 1,
  field_comment = 2,
  field_key = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_account_name] = "account_name",
  [field_comment] = "comment",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_account_name, 2},
  [1] =
    {field_account_name, 2},
    {field_comment, 3},
  [3] =
    {field_key, 0},
  [4] =
    {field_key, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == ' ') ADVANCE(33);
      if (lookahead == '#') ADVANCE(26);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == ':') ADVANCE(22);
      if (lookahead == ';') ADVANCE(24);
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == ',') ADVANCE(30);
      if (lookahead == ':') ADVANCE(22);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == 'c') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == 'c') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == 'n') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == 't') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(28);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == ' ') ADVANCE(33);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == ';') ADVANCE(23);
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_account);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_account);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_account_name_segment);
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead == ',') ADVANCE(30);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_tag_key);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_tag_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ',') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__spaces1);
      if (lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__spaces2);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_account] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_tag_key] = ACTIONS(1),
    [sym__spaces1] = ACTIONS(1),
    [sym__spaces2] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__definition] = STATE(2),
    [sym_account_directive] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_account] = ACTIONS(5),
    [sym__spaces1] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_account,
    ACTIONS(7), 1,
      sym__spaces1,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym__newline,
    STATE(3), 3,
      sym__definition,
      sym_account_directive,
      aux_sym_source_file_repeat1,
  [18] = 5,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_account,
    ACTIONS(20), 1,
      sym__spaces1,
    ACTIONS(23), 1,
      sym__newline,
    STATE(3), 3,
      sym__definition,
      sym_account_directive,
      aux_sym_source_file_repeat1,
  [36] = 5,
    ACTIONS(26), 1,
      sym__comment_word,
    ACTIONS(28), 1,
      sym_tag_key,
    STATE(20), 1,
      sym_tag,
    STATE(27), 1,
      sym_comment,
    STATE(28), 1,
      sym__comment,
  [52] = 1,
    ACTIONS(30), 4,
      ts_builtin_sym_end,
      anon_sym_account,
      sym__spaces1,
      sym__newline,
  [59] = 3,
    ACTIONS(32), 1,
      anon_sym_COLON,
    STATE(7), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(34), 2,
      sym__spaces2,
      sym__newline,
  [70] = 3,
    ACTIONS(32), 1,
      anon_sym_COLON,
    STATE(9), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(36), 2,
      sym__spaces2,
      sym__newline,
  [81] = 1,
    ACTIONS(38), 4,
      ts_builtin_sym_end,
      anon_sym_account,
      sym__spaces1,
      sym__newline,
  [88] = 3,
    ACTIONS(40), 1,
      anon_sym_COLON,
    STATE(9), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(43), 2,
      sym__spaces2,
      sym__newline,
  [99] = 1,
    ACTIONS(45), 4,
      ts_builtin_sym_end,
      anon_sym_account,
      sym__spaces1,
      sym__newline,
  [106] = 4,
    ACTIONS(26), 1,
      sym__comment_word,
    ACTIONS(28), 1,
      sym_tag_key,
    STATE(20), 1,
      sym_tag,
    STATE(30), 1,
      sym__comment,
  [119] = 4,
    ACTIONS(26), 1,
      sym__comment_word,
    ACTIONS(28), 1,
      sym_tag_key,
    STATE(20), 1,
      sym_tag,
    STATE(31), 1,
      sym__comment,
  [132] = 3,
    ACTIONS(47), 1,
      sym__spaces2,
    ACTIONS(49), 1,
      sym__newline,
    STATE(26), 1,
      sym__inline_comment,
  [142] = 2,
    ACTIONS(53), 1,
      sym_tag_value,
    ACTIONS(51), 2,
      anon_sym_COMMA,
      sym__newline,
  [150] = 1,
    ACTIONS(43), 3,
      anon_sym_COLON,
      sym__spaces2,
      sym__newline,
  [156] = 2,
    ACTIONS(55), 1,
      sym_account_name_segment,
    STATE(13), 1,
      sym_account_name,
  [163] = 1,
    ACTIONS(57), 2,
      anon_sym_SEMI,
      anon_sym_POUND,
  [168] = 2,
    ACTIONS(59), 1,
      sym__spaces1,
    ACTIONS(61), 1,
      sym__newline,
  [175] = 2,
    ACTIONS(63), 1,
      sym__spaces1,
    ACTIONS(65), 1,
      sym__newline,
  [182] = 2,
    ACTIONS(65), 1,
      sym__newline,
    ACTIONS(67), 1,
      anon_sym_COMMA,
  [189] = 1,
    ACTIONS(69), 2,
      anon_sym_COMMA,
      sym__newline,
  [194] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [198] = 1,
    ACTIONS(73), 1,
      sym__spaces1,
  [202] = 1,
    ACTIONS(75), 1,
      sym__newline,
  [206] = 1,
    ACTIONS(77), 1,
      sym_account_name_segment,
  [210] = 1,
    ACTIONS(79), 1,
      sym__newline,
  [214] = 1,
    ACTIONS(81), 1,
      sym__newline,
  [218] = 1,
    ACTIONS(83), 1,
      sym__newline,
  [222] = 1,
    ACTIONS(85), 1,
      sym__spaces1,
  [226] = 1,
    ACTIONS(87), 1,
      sym__newline,
  [230] = 1,
    ACTIONS(89), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 52,
  [SMALL_STATE(6)] = 59,
  [SMALL_STATE(7)] = 70,
  [SMALL_STATE(8)] = 81,
  [SMALL_STATE(9)] = 88,
  [SMALL_STATE(10)] = 99,
  [SMALL_STATE(11)] = 106,
  [SMALL_STATE(12)] = 119,
  [SMALL_STATE(13)] = 132,
  [SMALL_STATE(14)] = 142,
  [SMALL_STATE(15)] = 150,
  [SMALL_STATE(16)] = 156,
  [SMALL_STATE(17)] = 163,
  [SMALL_STATE(18)] = 168,
  [SMALL_STATE(19)] = 175,
  [SMALL_STATE(20)] = 182,
  [SMALL_STATE(21)] = 189,
  [SMALL_STATE(22)] = 194,
  [SMALL_STATE(23)] = 198,
  [SMALL_STATE(24)] = 202,
  [SMALL_STATE(25)] = 206,
  [SMALL_STATE(26)] = 210,
  [SMALL_STATE(27)] = 214,
  [SMALL_STATE(28)] = 218,
  [SMALL_STATE(29)] = 222,
  [SMALL_STATE(30)] = 226,
  [SMALL_STATE(31)] = 230,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_name, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_name, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_directive, 4, 0, 1),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_account_name_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_account_name_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_directive, 5, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_comment, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 4),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_comment, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hledger(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hledger",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
