/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_account = 1,
  anon_sym_COLON = 2,
  anon_sym_SEMI = 3,
  anon_sym_POUND = 4,
  sym_account_name_segment = 5,
  sym__comment_word = 6,
  sym__spaces1 = 7,
  sym__spaces2 = 8,
  sym__newline = 9,
  sym_source_file = 10,
  sym__definition = 11,
  sym_account_directive = 12,
  sym_account_name = 13,
  sym__inline_comment = 14,
  sym_comment = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_account_name_repeat1 = 17,
  aux_sym_comment_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_account] = "account",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_POUND] = "#",
  [sym_account_name_segment] = "account_name_segment",
  [sym__comment_word] = "_comment_word",
  [sym__spaces1] = "_spaces1",
  [sym__spaces2] = "_spaces2",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_account_directive] = "account_directive",
  [sym_account_name] = "account_name",
  [sym__inline_comment] = "_inline_comment",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_account_name_repeat1] = "account_name_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_account] = anon_sym_account,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_account_name_segment] = sym_account_name_segment,
  [sym__comment_word] = sym__comment_word,
  [sym__spaces1] = sym__spaces1,
  [sym__spaces2] = sym__spaces2,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_account_directive] = sym_account_directive,
  [sym_account_name] = sym_account_name,
  [sym__inline_comment] = sym__inline_comment,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_account_name_repeat1] = aux_sym_account_name_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_account] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_account_name_segment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_word] = {
    .visible = false,
    .named = true,
  },
  [sym__spaces1] = {
    .visible = false,
    .named = true,
  },
  [sym__spaces2] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_account_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_account_name] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_account_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_account_name = 1,
  field_comment = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_account_name] = "account_name",
  [field_comment] = "comment",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_account_name, 2},
  [1] =
    {field_account_name, 2},
    {field_comment, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == 'c') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == ';') ADVANCE(16);
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_account);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_account);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_account_name_segment);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead == 'c') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead == 'n') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead == 'o') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead == 't') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead == 'u') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__comment_word);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__spaces1);
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__spaces2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_account] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym__comment_word] = ACTIONS(1),
    [sym__spaces1] = ACTIONS(1),
    [sym__spaces2] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym__definition] = STATE(2),
    [sym_account_directive] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_account] = ACTIONS(5),
    [sym__spaces1] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_account,
    ACTIONS(7), 1,
      sym__spaces1,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym__newline,
    STATE(3), 3,
      sym__definition,
      sym_account_directive,
      aux_sym_source_file_repeat1,
  [18] = 5,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_account,
    ACTIONS(20), 1,
      sym__spaces1,
    ACTIONS(23), 1,
      sym__newline,
    STATE(3), 3,
      sym__definition,
      sym_account_directive,
      aux_sym_source_file_repeat1,
  [36] = 1,
    ACTIONS(26), 4,
      ts_builtin_sym_end,
      anon_sym_account,
      sym__spaces1,
      sym__newline,
  [43] = 3,
    ACTIONS(28), 1,
      anon_sym_COLON,
    STATE(6), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(30), 2,
      sym__spaces2,
      sym__newline,
  [54] = 3,
    ACTIONS(28), 1,
      anon_sym_COLON,
    STATE(7), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(32), 2,
      sym__spaces2,
      sym__newline,
  [65] = 3,
    ACTIONS(34), 1,
      anon_sym_COLON,
    STATE(7), 1,
      aux_sym_account_name_repeat1,
    ACTIONS(37), 2,
      sym__spaces2,
      sym__newline,
  [76] = 1,
    ACTIONS(39), 4,
      ts_builtin_sym_end,
      anon_sym_account,
      sym__spaces1,
      sym__newline,
  [83] = 1,
    ACTIONS(41), 4,
      ts_builtin_sym_end,
      anon_sym_account,
      sym__spaces1,
      sym__newline,
  [90] = 3,
    ACTIONS(43), 1,
      sym__spaces2,
    ACTIONS(45), 1,
      sym__newline,
    STATE(25), 1,
      sym__inline_comment,
  [100] = 1,
    ACTIONS(37), 3,
      anon_sym_COLON,
      sym__spaces2,
      sym__newline,
  [106] = 3,
    ACTIONS(47), 1,
      sym__spaces1,
    ACTIONS(49), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym_comment_repeat1,
  [116] = 3,
    ACTIONS(47), 1,
      sym__spaces1,
    ACTIONS(51), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym_comment_repeat1,
  [126] = 3,
    ACTIONS(53), 1,
      sym__spaces1,
    ACTIONS(56), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym_comment_repeat1,
  [136] = 2,
    ACTIONS(58), 1,
      sym_account_name_segment,
    STATE(10), 1,
      sym_account_name,
  [143] = 2,
    ACTIONS(60), 1,
      sym__spaces1,
    ACTIONS(62), 1,
      sym__newline,
  [150] = 1,
    ACTIONS(64), 2,
      anon_sym_SEMI,
      anon_sym_POUND,
  [155] = 2,
    ACTIONS(66), 1,
      sym__comment_word,
    STATE(24), 1,
      sym_comment,
  [162] = 1,
    ACTIONS(56), 2,
      sym__spaces1,
      sym__newline,
  [167] = 1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
  [171] = 1,
    ACTIONS(70), 1,
      sym__spaces1,
  [175] = 1,
    ACTIONS(72), 1,
      sym__newline,
  [179] = 1,
    ACTIONS(74), 1,
      sym_account_name_segment,
  [183] = 1,
    ACTIONS(76), 1,
      sym__newline,
  [187] = 1,
    ACTIONS(78), 1,
      sym__newline,
  [191] = 1,
    ACTIONS(80), 1,
      sym__comment_word,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 43,
  [SMALL_STATE(6)] = 54,
  [SMALL_STATE(7)] = 65,
  [SMALL_STATE(8)] = 76,
  [SMALL_STATE(9)] = 83,
  [SMALL_STATE(10)] = 90,
  [SMALL_STATE(11)] = 100,
  [SMALL_STATE(12)] = 106,
  [SMALL_STATE(13)] = 116,
  [SMALL_STATE(14)] = 126,
  [SMALL_STATE(15)] = 136,
  [SMALL_STATE(16)] = 143,
  [SMALL_STATE(17)] = 150,
  [SMALL_STATE(18)] = 155,
  [SMALL_STATE(19)] = 162,
  [SMALL_STATE(20)] = 167,
  [SMALL_STATE(21)] = 171,
  [SMALL_STATE(22)] = 175,
  [SMALL_STATE(23)] = 179,
  [SMALL_STATE(24)] = 183,
  [SMALL_STATE(25)] = 187,
  [SMALL_STATE(26)] = 191,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_name, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_name, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_account_name_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_account_name_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_directive, 4, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account_directive, 5, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_comment, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_comment, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hledger(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hledger",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
